package com.pandev.academy.mysubmissionapplication;

import java.util.ArrayList;

public class ClubData {
    public static String[][] data = new String[][]{
            {"Manchester United", "The Red Devils", "1878", "Old Trafford", "Ole Gunnar Solskjaer", "Premier League", "https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/220px-Manchester_United_FC_crest.svg.png", "Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878, klub ini berganti nama menjadi Manchester United pada 1902 dan pindah ke Old Trafford pada tahun 1910.\n" +
                    "\n" +
                    "Manchester United telah memenangkan banyak trofi di sepak bola Inggris, termasuk rekor 20 gelar Liga, 12 Piala FA, 4 Piala Liga dan rekor 21 FA Community Shield. Klub ini juga telah memenangkan tiga Piala Eropa, satu Piala UEFA, satu Piala Winners UEFA, satu Piala Super UEFA, satu Piala Interkontinental dan satu Piala Dunia Antarklub FIFA. Pada 1998-1999, klub memenangkan treble dari Liga Premier, Piala FA dan Liga Champions, prestasi belum pernah terjadi sebelumnya untuk klub Inggris."},
            {"Arsenal", "The Gunners", "1886", "Emirates", "Unai Emery", "Premier League", "https://upload.wikimedia.org/wikipedia/id/thumb/5/53/Arsenal_FC.svg/180px-Arsenal_FC.svg.png", "Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 13 gelar di Piala FA (Gelar paling banyak). Arsenal memegang rekor untuk periode terpanjang berada di kasta puncak Liga Inggris tanpa pernah terdegradasi sejak musim 1919 dan menjadi tim pada peringkat pertama dalam klasemen Liga Inggris sepanjang abad ke-20. Arsenal menjadi tim kedua di Inggris yang menyelesaikan semusim liga tanpa kalah (musim 2003–04) dan tim pertama yang melakukannya pada era di mana satu musim berlangsung 38 pertandingan.\n" +
                    "\n" +
                    "Arsenal didirikan pada 1886 di Woolwich dan pada tahun 1893 menjadi klub pertama dari selatan Inggris untuk bergabung dengan Football League. Pada tahun 1913, hal itu bergerak ke utara melintasi kota Stadion Arsenal di Highbury. Pada 1930, klub telah memenangkan lima gelar Liga Championship dan dua Piala FA. Setelah periode bersandar pada tahun-tahun pasca-perang itu memenangkan Liga dan Piala FA ganda, di musim 1970-71, dan pada 1990-an dan dekade pertama abad ke-21 memenangkan dua gelar ganda dan mencapai Final Liga Champions UEFA 2006."},
            {"Liverpool", "The Reds", "1892", "Anfield", "Jurgen Klopp", "Premier League", "https://upload.wikimedia.org/wikipedia/id/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png", "Liverpool Football Club (dikenal pula sebagai Liverpool atau The Reds) adalah sebuah klub sepak bola asal Inggris yang berbasis di Kota Liverpool. Saat ini Liverpool adalah peserta Liga Utama Inggris. Liverpool juga merupakan juara bertahan Liga Champions UEFA musim 2018-2019\n" +
                    "\n" +
                    "Liverpool telah memenangkan 6 trofi Liga Champions UEFA (dulu Piala Champions) dan merupakan klub dengan pemegang gelar juara Liga Champions UEFA terbanyak di Inggris dan ketiga di Eropa setelah Real Madrid dan AC Milan. Selain itu Liverpool juga pemegang 3 gelar juara Liga Eropa UEFA dan 4 gelar Piala Super UEFA. Di kompetisi domestik, Liverpool adalah klub dengan 18 gelar juara Liga Inggris, 7 Piala FA, serta 7 kali juara Piala Liga."},
            {"Chelsea", "The Blues", "1905", "Stamford Bridge", "Frank Lampard", "Premier League", "https://upload.wikimedia.org/wikipedia/id/thumb/c/cc/Chelsea_FC.svg/200px-Chelsea_FC.svg.png", "Chelsea Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris.\n" +
                    "\n" +
                    "Kesuksesan pertama Chelsea diraih saat meraih gelar juara liga pada tahun 1955. Beberapa gelar dari berbagai kompetisi juga berhasil diraih pada dekade 1960an, 1970an, 1990an, dan 2000an. Sepanjang sejarah penampilan dalam dunia sepak bola di Inggris dan Eropa, Chelsea telah meraih enam gelar juara Liga Utama Inggris, delapan Piala FA, lima Piala Liga, dua Liga Eropa UEFA, dua Piala Winners UEFA, satu Liga Champions UEFA, dan satu Piala Super UEFA. Dalam dua dekade terakhir merupakan periode terbaik kesuksesan Chelsea dengan meraih lebih dari 30 gelar sejak tahun 1997, termasuk untuk pertama kali meraih gelar ganda, Liga Utama Inggris dan Piala FA pada tahun 2010 serta gelar juara Liga Champions UEFA pada tahun 2012 dan Liga Eropa UEFA pada 2013 dan 2019."},
            {"Juventus", "[La] Vecchia Signora", "1897", "Allianz", "Maurizio Sarri", "Serie A", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Juventus_FC_2017_logo.svg/100px-Juventus_FC_2017_logo.svg.png", "Juventus Football Club, biasa disebut sebagai Juventus dan popular dengan nama Juve, adalah klub sepak bola profesional Italia yang berbasis di Turin, Piedmont. Klub sepak bola ini adalah yang tertua ketiga di Italia dan telah menghabiskan sebagian besar sejarahnya, dengan pengecualian pada musim 2006–07, di atas klasemen Divisi Pertama (dikenal sebagai Serie A sejak 1929).\n" +
                    "\n" +
                    "Didirikan pada tahun 1897 sebagai Sport Club Juventus oleh sekelompok siswa muda di kota Turin, yang dipimpin oleh Eugenio Canfari dan saudaranya Enrico, klub ini kemudian dikelola oleh industrialis keluarga Agnelli sejak tahun 1923, yang merupakan kemitraan olahraga tertua di Italia, sehingga membuat Juventus menjadi klub profesional pertama di negara itu. Seiring waktu, klub telah menjadi simbol dari budaya bangsa dan Italianità (\"Italia\"), karena tradisi mereka sukses, beberapa di antaranya memiliki dampak yang signifikan dalam masyarakat Italia, terutama pada tahun 1930-an dan dekade pertama pasca-perang yang sekaligus mempengaruhi politik ideologis dan asal sosial ekonomi simpatisan klub. Hal ini tercermin antara lain, dalam kontribusi klub untuk tim nasional sepak bola Italia sejak paruh kedua tahun 1920-an yang kemudian diakui sebagai salah satu yang paling berpengaruh dalam sepak bola internasional karena turut berperan penting dalam kemenangan Piala Dunia 1934, 1982 dan 2006. Basis penggemar klub ini lebih besar daripada klub sepak bola Italia lainnya dan merupakan salah satu yang terbesar di seluruh dunia. Dukungan untuk Juventus tersebar luas di seluruh negeri dan luar negeri, terutama di negara-negara dengan keberadaan yang signifikan dari imigran Italia."},
            {"A.C. Milan", "i Rossoneri", "1899", "San Siro", "Marco Giampaolo", "Serie A", "https://upload.wikimedia.org/wikipedia/id/thumb/1/17/AC_Milan.png/120px-AC_Milan.png", "Associazione Calcio Milan, sering disebut sebagai A.C. Milan atau hanya Milan, adalah sebuah klub sepak bola Italia yang berbasis di Milan, Lombardia, yang bermain di Serie A. Mereka bermain dengan seragam bergaris merah-hitam dan celana putih (kadang-kadang hitam), sehingga dijuluki rossoneri (\"merah-hitam\"). Milan adalah tim tersukses kedua dalam sejarah persepak bolaan Italia, menjuarai Serie A 18 kali dan Piala Italia 5 kali.\n" +
                    "\n" +
                    "AC Milan adalah klub tersukses ke-4 di dunia sepak bola dalam hal jumlah piala internasional bersama Boca Juniors dengan 18 gelar resmi dari UEFA dan FIFA dibawah Real Madrid, FC Barcelona, dan Al-Ahly. Milan telah memenangkan rekor tiga Piala Interkontinental dan setelah penggantinya, Piala Dunia Antarklub FIFA. Milan juga memenangkan Piala Liga Eropa/Champions tujuh kali. yang kedua setelah Real Madrid. Mereka juga memenangkan rekor Piala Super UEFA lima kali dan Piala Winners UEFA dua kali. Milan memenangkan setiap kompetisi besar di mana ia telah berkompetisi, terkecuali untuk Liga Eropa UEFA (dalam kompetisi ini mereka telah kehilangan dua semifinal pada tahun 1972 dan pada tahun 2002). Secara domestik, dengan 18 gelar liga. Milan adalah gabungan kedua klub paling sukses di Serie A di belakang Juventus (31 gelar), bersama dengan rival lokal Inter.[8] Mereka juga telah memenangkan Coppa Italia lima kali, serta rekor enam kemenangan Supercoppa Italiana."},
            {"Inter Milan", "I Nerazzurri", "1908", "San Siro", "Antonio Conte", "Serie A", "https://upload.wikimedia.org/wikipedia/id/thumb/2/23/Inter_Milan.png/200px-Inter_Milan.png", "Football Club Internazionale Milano, atau yang dikenal dengan nama Internazionale ataupun juga Inter, dan bahasa sehari-hari dikenal sebagai Inter Milan di luar Italia, adalah sebuah klub sepak bola profesional asal Italia yang saat ini bermain di Serie A Liga Italia. Inter Milan mempunyai julukan sebagai il Nerazzurri (si biru hitam), il Biscone (si ular besar), dan juga La Beneamata (yang tersayang). Klub bermain di Serie A (divisi pertama) sejak tahun 1908, dan pendukung Internazionale disebut Interisti.\n" +
                    "\n" +
                    "Dari tahun 2006 hingga tahun 2010 adalah tahun pencapaian terbaik kedua bagi Inter sepanjang sejarah sejak berdiri. Dalam kurun waktu tersebut mereka sukses memperoleh lima gelar yaitu Serie A, Coppa Italia, Liga Champions UEFA, Piala Super Italia, dan Piala Dunia Antarklub FIFA."},
            {"Barcelona", "Blaugrana", "1899", "Camp Nou", "Ernesto Valverde", "La Liga", "https://upload.wikimedia.org/wikipedia/id/thumb/4/47/FC_Barcelona_%28crest%29.svg/225px-FC_Barcelona_%28crest%29.svg.png", "Fútbol Club Barcelona, juga dikenal sebagai Barcelona atau Barça, adalah klub sepak bola profesional yang berbasis di Barcelona, Catalunya, Spanyol.\n" +
                    "\n" +
                    "Didirikan pada tahun 1899 oleh sekelompok pemain Swiss, Inggris dan Catalan yang dipimpin oleh Joan Gamper, klub telah menjadi simbol budaya Catalan dan Catalanisme, yang mempunyai motto \"Més que un club\" (Lebih dari sebuah klub). Tidak seperti banyak klub sepak bola lainnya, para pendukung memiliki dan mengoperasikan Barcelona. Ia adalah klub sepak bola kedua terkaya di dunia dalam hal pendapatan, dengan omset tahunan sebesar €560,8 juta dan kedua yang paling berharga, senilai $3,56 miliar. Lagu kebangsaan resmi Barcelona adalah \"Cant del Barça\", yang ditulis oleh Jaume Picas dan Josep Maria Espinas.\n" +
                    "\n" +
                    "Klub ini masuk menjadi peserta Primera División (Divisi Utama) sejak tahun 1928, dan bersama-sama Real Madrid dan Athletic Bilbao menjadi tim yang tak pernah terdegradasi ke Segunda División (Divisi Dua). Klub ini juga menjadi klub yang menjuarai liga Spanyol pertama kali. Dengan persembahan 23 gelar Liga Spanyol, 25 gelar Copa del Rey, 10 gelar Piala Super Spanyol, 5 gelar Liga Champions Eropa, 4 gelar Piala UEFA, 4 gelar Piala Super Eropa, FC Barcelona menjadi salah satu tim tersukses di Spanyol, Eropa, dan dunia. Bukti paling nyata ketika pada tahun 2009 FC Barcelona berhasil menjadi klub Spanyol pertama yang berhasil meraih gelar Treble (juara La Liga, Copa del Rey, dan Liga Champions). Dilanjutkan dengan raihan gelar Piala Super Spanyol, Piala Super Eropa dan Piala Dunia Antarklub FIFA untuk melengkapi raihan gelarnya menjadi Sextuples. Barcelona merupakan klub sepak bola pertama di dunia yang melakukan raihan ini. Penggemar Barca juga sering disebut Culés."},
            {"Real Madrid", "Los Blancos", "1902", "Santiago Bernabeu", "Zinedine Zidane", "La Liga", "https://upload.wikimedia.org/wikipedia/id/thumb/8/8b/Real_Madrid_Club_de_F%C3%BAtbol.png/175px-Real_Madrid_Club_de_F%C3%BAtbol.png", "Real Madrid Club de Fútbol, umumnya dikenal sebagai Real Madrid, adalah klub sepak bola profesional yang berbasis di Madrid, Spanyol.\n" +
                    "\n" +
                    "Didirikan pada tahun 1902 sebagai Madrid Football Club, secara tradisional mengenakan kostum kandang putih. Kata Real (\"dari kerajaan\") Spanyol dan dianugerahkan ke klub oleh Raja Alfonso XIII pada tahun 1920 bersama-sama dengan mahkota kerajaan di lambang klub. Klub ini telah memainkan pertandingan kandang di Stadion Santiago Bernabéu dengan kapasitas 85.454 di pusat kota Madrid sejak tahun 1947.\n" +
                    "\n" +
                    "Klub ini adalah klub sepak bola terkaya di dunia dalam hal pendapatan, dengan omset tahunan sebesar €513 juta dan paling berharga, senilai €3.3 miliar. Ini adalah salah satu dari tiga klub untuk tidak pernah terdegradasi dari papan atas sepak bola Spanyol, bersama dengan Athletic Bilbao dan Barcelona. Real Madrid memiliki banyak persaingan lama, terutama El Clásico dengan Barcelona dan El Derbi madrileño dengan Atlético Madrid."},
            {"Bayern Munchen", "Die Bayern", "1900", "Allianz Arena", "Nico Kovac", "Bundesliga", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/220px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png", "Futball-Club Bayern München e.V., juga dikenal sebagai FC Bayern München, atau FC Bayern, adalah sebuah klub olahraga Jerman yang berbasis di München, Bavaria. Hal ini terkenal karena tim sepak bola profesional, yang bermain di Bundesliga, peringkat teratas sistem liga sepak bola Jerman, dan merupakan klub paling sukses dalam sejarah sepak bola Jerman, setelah memenangkan rekor 29 gelar nasional dan 19 piala nasional.\n" +
                    "FC Bayern didirikan pada tahun 1900 oleh sebelas pemain sepak bola yang dipimpin oleh Franz John. Meskipun Bayern memenangkan kejuaraan nasional pertamanya pada tahun 1932, klub tersebut tidak dipilih untuk Bundesliga pada awal tahun 1963. Klub memiliki periode yang sukses terbesar di tengah tahun 1970-an, di bawah kapten dari Franz Beckenbauer, memenangkan Piala Eropa tiga kali berturut-turut (1974-1976). Secara keseluruhan, Bayern telah mencapai sepuluh final Piala Eropa/Liga Champions, yang terakhir memenangkan gelar kelima mereka pada tahun 2013 sebagai bagian dari treble benua. Bayern juga telah memenangkan satu Piala UEFA, satu Piala Winners UEFA, satu Piala Super UEFA, dua Piala Interkontinental dan satu Piala Dunia Antarklub FIFA, membuatnya menjadi salah satu klub Eropa yang paling sukses di dunia. Sejak pembentukan Bundesliga, Bayern telah menjadi klub yang dominan dalam sepak bola Jerman dengan 28 gelar dan telah memenangkan 10 dari 14 gelar terakhir. Mereka memiliki persaingan lokal tradisional dengan TSV 1860 München dan 1. FC Nürnberg, serta persaingan kontemporer dengan Borussia Dortmund.\n" +
                    "\n"},
            {"Borussia Dortmund", "Die Borussen", "1909", "Signal Iduna Park", "Lucien Favre", "Bundesliga", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Borussia_Dortmund.png/200px-Borussia_Dortmund.png", "Ballspielverein Borussia 09 e.V. Dortmund umumnya dikenal sebagai Borussia Dortmund, Dortmund, atau BVB, adalah klub sepak bola di Jerman berbasis di kota Dortmund, Nordrhein-Westfalen. Tim ini bermain di Bundesliga dan termasuk salah satu klub yang paling sukses di sejarah Sepak Bola Jerman.\n" +
                    "Borussia Dortmund didirikan pada tahun 1909 oleh tujuh belas pemain Sepak Bola dari Dortmund. Borussia Dortmund telah memenangkan delapan kejuaraan Bundesliga, tiga DFB-Pokal empat DFL-Supercup, satu UEFA Champions League satu Piala Winners UEFA, dan satu Interkontinental Cup. Mereka memenangkan Piala Winners UEFA pada tahun 1966 dan tim ini menjadi klub Jerman pertama yang memenangkan gelar di Eropa.\n"}
    };

    public static ArrayList<ClubFootball> getListData(){
        ArrayList<ClubFootball> list = new ArrayList<>();
        for (String[] aData : data){
            ClubFootball clubFootball = new ClubFootball();
            clubFootball.setClubName(aData[0]);
            clubFootball.setClubNickName(aData[1]);
            clubFootball.setClubSince(aData[2]);
            clubFootball.setClubStadium(aData[3]);
            clubFootball.setClubManager(aData[4]);
            clubFootball.setClubLeague(aData[5]);
            clubFootball.setClubPhoto(aData[6]);
            clubFootball.setClubAbout(aData[7]);

            list.add(clubFootball);

        }

        return list;
    }

}
